document.addEventListener("DOMContentLoaded", () => {
  const p      = new URLSearchParams(location.search);
  const domain = p.get('domain') || 'Unknown domain';
  const reason = (p.get('reason') || '').toLowerCase();

  document.getElementById('domain').textContent = domain;

  const badge    = document.getElementById('badge');
  const reasonEl = document.getElementById('reason');

  if (reason.includes('tunnel')) {
    badge.className = 'badge tunneling';
    badge.textContent = 'DNS Tunneling';
    reasonEl.textContent = 'This domain is performing DNS tunneling — a technique used to secretly exfiltrate data through DNS queries.';
  } else if (reason.includes('dga')) {
    badge.className = 'badge dga';
    badge.textContent = 'DGA Domain';
    reasonEl.textContent = 'This domain was generated by a Domain Generation Algorithm (DGA), a technique used by malware to contact command-and-control servers.';
  } else if (reason.includes('blacklist') || reason.includes('manual') || reason.includes('previously')) {
    badge.className = 'badge blacklist';
    badge.textContent = 'Blacklisted';
    reasonEl.textContent = 'This domain is on your Secure DNS Query blacklist and has been blocked.';
  } else {
    badge.className = 'badge dga';
    badge.textContent = 'Malicious';
    reasonEl.textContent = 'This domain was identified as malicious by the Secure DNS Query ML engine.';
  }

  // Setup Back Button
  document.getElementById('btn-back').addEventListener('click', () => {
    if (history.length > 1) {
      history.back();
    } else {
      window.close();
    }
  });

  // Setup Proceed Button
  document.getElementById('btn-proceed').addEventListener('click', () => {
    if (confirm('⚠️ This domain was flagged as malicious.\n\nProceeding may expose your device to threats.\n\nContinue to ' + domain + '?')) {
      chrome.runtime.sendMessage({ type: 'BYPASS_DOMAIN', domain: domain }, () => {
        location.href = 'https://' + domain;
      });
    }
  });

  // Setup Dynamic Dashboard Link
  chrome.storage.local.get(["server"], (r) => {
    const server = r.server || "http://localhost:5000";
    const dashLink = document.getElementById('link-dashboard');
    if (dashLink) {
      dashLink.href = server + "/dashboard";
      dashLink.target = "_blank";
    }
  });
});
